language: scala
jdk:
  - openjdk8

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    # default stage is test
    - name: Scalafmt
      script: ./bin/scalafmt --test
    - env: Scala 2.13
      script: sbt "++2.13.1 test"
    - env: Scala 2.12
      script: sbt test plugin/scripted
    - env: Scala 2.11
      script: sbt "++2.11.12 test"
    - env: Scala 2.12
      script: sbt test plugin/scripted
      jdk: openjdk11
    - stage: release
      script: sbt ci-release docs/docusaurusPublishGhpages

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local
